version: '3'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

