version: '3'

services:
  frontend:
    build:
      context: ./client
    ports:
      ["80:80"]

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
